### ISSUE TITLE
Kann content nicht importieren. 

### ISSUE THREAD

**Issue by Trashloot** [himmelweiss/dsa5-aventuria-map#1]
Hey ehm sry falls ich mich dumm anstelle, 

Ich habe mittlerweile rausgefunden, dass ich im Journalbrowser den Import/Update Button drücken muss. (Stand das eigentlich irgendwo ? Ich hab das nur durch umherstolpern gefunden). Aber bei mir werden nur leere Ordner im Notizbuch erstellt. Ich bin mir gerade unsicher ob das Modul hängt, ob der Kontent nicht importiert werden kann, weil ich irgendwas falsch gemacht habe, ob das Modul einfach nur lange braucht oder ob Foundry nicht die Berechtigung hat in Ordner zu schreiben, die das Modul benötigt. 

Wäre cool zu wissen wohin das Modul die Daten exportiert. Bisher hatte ich nie Probleme damit Journaleinträge zu importieren aber ich hab auch noch nie ein Modul gehabt, was mir ne Szene erstellt und Notizen darauf verlinkt. Ich würde einfach gerne mal in die Ordner gucken und nach schauen wollen ob diese vielleicht schreib geschützt sind oder ob da vielleicht schon Daten abgelegt werden. 

Oh und ich wünsch natürlich einen fantastischen Sonntag. Ich brauch nicht sofort ne Antwort :D.

Mit freundlichem Gruß, 
Max

**Comment by himmelweiss** [comment]
Hallo Trashloot,

versuche mal das DSA System zu aktualisieren, danach sollte es eigentlich gehen.
Und natürlich auch das DSA Core Modul für die hires Aventurien Karte.
Vor erneutem Import am besten das vom vorherigen Import zuerst löschen.

Der Import selbst dauert eigentlich nur ca. 10 Sekunden, je nach Rechenleistung natürlich ein paar Sekunden länger oder kürzer.

Ja, auf den Import wird hingewiesen im Chat wie bei den anderen DSA Modulen wenn man diese das erste mal installiert/aktiviert.

Das Modul exportiert die Notizbucheinträge unter einem Hauptordner "DSA5 Interaktive Aventurienkarte" (mit recht vielen Unterordnern) und natürlich noch die Szene selbst, ebenfalls dann unter "DAS5 Interaktive Aventurienkarte" im Reiter Szenen.
Leere Ordner dürfen dabei nicht entstehen, wenn dem so ist dann ist etwas schief gelaufen. 

Ebenfalls noch einen schönen ruhigen Sonntag!

**Comment by Trashloot** [comment]
Ich hab gerade eben erst alles geupdatet. Aber mir ist aufgefallen, dass die "Unterordner bei mir ins Hauptverzeichnis geworfen werden und der Ordner "DSA5 Interaktive Aventurienkarte" Nicht erstellt wird. Habe bereits versucht alles zu löschen und nur auf den Importieren Knopf zu drücken UND in einem dritten Versuch vorher die Szene importiert und danach auf den Importieren Knopf gedrückt. Ich habe den Ordner "DSA5 Interaktive Aventurienkarte" auch schon einmal händisch erstellt und wieder wurde bei mir alles nur ins Hauptverzeichnis geworfen. 

Es werden in jedem Fall aber nur die leeren Ordner erstellt. Nicht einmal die Szene. Der "Importieren" Knopf hat auch konstant den Ladebalken. Es kommt keine Fehlermeldung.

**Comment by himmelweiss** [comment]
Das darf so natürlich nicht sein, sollte alles in den Hauptordner gelangen.
Habe es gerade eben auch nochmal probiert und es hat funktioniert.

Auch wenn du erst die Updates gemacht hast, trotzdem nur zum Abgleich:
DSA5 System Version 3.2.3 installiert?
DSA5 Core Rules Version 3.2.0 ist installiert?

Falls ja, bitte dann mal in einer TEST Welt probieren mit nur dem DSA5 System und dem DSA5 Core Modul.

**Comment by Trashloot** [comment]
![image](https://user-images.githubusercontent.com/50813236/155889388-e267d8c2-20a4-461e-a811-6f418e5e0c1e.png)
![image](https://user-images.githubusercontent.com/50813236/155889436-821c11ef-ef4d-421c-bd57-2a5a5a38434a.png)
![image](https://user-images.githubusercontent.com/50813236/155889458-0d077bf6-7f15-4bbf-9e35-6cf5e0703766.png)
![image](https://user-images.githubusercontent.com/50813236/155889403-9bf221ae-9a30-4de6-9291-9bf13693e0c4.png)

![image](https://user-images.githubusercontent.com/50813236/155889537-64c2eb9f-c95e-4dfb-a159-a9cf2c6b1c8a.png)
Das ist jetzt ne komplett frische Welt. 

Die Tatsache, dass ich die Linux Version von Foundry auf nem Server laufen habe, dürfte ja keinen Unterschied machen, oder ? Foundry ist ja Foundry.

**Comment by Trashloot** [comment]
Fuck ich bin dumm. Habe eben gesehen, dass das Sytem nicht geupdatet wird, wenn man Update All in den Modulen anklickt. Gib mir ne Sekunde.

**Comment by Trashloot** [comment]
Jap funktioniert jetzt. Sry dass ich gestört habe. Ich hab vergessen das System upzudaten. Da die Module sich nur für die Foundry Version interessieren und keine Fehlermeldung bringen, wenn das System veraltet ist, ist es mir selber nicht aufgefallen. Dazu kam noch, dass mein System auf der Version 3.0.2 war, was sehr ähnlich zu 3.2 aussieht. Sry nochmal und vielen Dank für die schnelle Hilfe. :D

**Comment by himmelweiss** [comment]
Du störst ganz sicher nicht, und du bist auch ganz sicher nicht dumm!
Freut mich das es jetzt klappt!
