### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by sirgawain111** [himmelweiss/dsa5-aventuria-map#2]
Bitte korrigiert den Copyright-Vermerk dahingehend, dass dies nur auf die Aventurienkarte  zutrifft.
Ausweislich einer Aussage von Himmelweiss in einem Discord-Channel stammt die große Mehrheit der Texte in diesem Modul aus der Wiki-Aventurica, und deren Inhalte stehen unter der CC-BY-SA-3.0-Lizenz.
Bitte sorgt dafür, dass a) die Bestimmungen dieser Lizenz eingehalten werden und b) Ulisses für diese Inhalte kein Copyright beansprucht.

**Comment by himmelweiss** [comment]
Hallo @sirgawain111,

Vielen Dank für den Hinweis.

Habe die Wiki Aventurica Lizenzbestimmungen auf der Foundy description page, GitHub Readme und in VTT hinzugefügt.
Falls diesbezüglich noch Unklarheiten bestehen sollten bitte an primetide oder an mich direkt wenden, am besten über Discord.
Denn ich will selbstverständlich mit solchen Geschichten wie mit diesem Foundry Modul hier niemanden auf die Füße treten.

![wikilicense](https://user-images.githubusercontent.com/7482909/156182606-df7d5215-af60-4e51-a8db-126cb3f42d92.jpg)
