### ISSUE TITLE
Karte ist nur schwarz beim spielen im Webbrowser

### ISSUE THREAD

**Issue by Voidi** [himmelweiss/dsa5-aventuria-map#4]
Installation und Import des Moduls läuft soweit ich das erkennen ohne Fehlermeldung durch.
Beim spielen über Firefox auf Linux tritt dann allerdings folgendes auf:
Beim aktivieren der Szene werden die Kartenpins werden geladen und sind auch benutzbar, aber die eigentliche Hintergrundgrafik ist nicht sichtbar. Auch in einer eigenen neuangelegten Szene wo ich manuell 'aventurien_hires.webp' als Hintergrundbild nehme wird das im Browser nicht geladen. Kann es sein das Webbrowser irgendwelche Probleme mit diesem große Bild hat?
Bei Benutzung über Chrome, Firefox auf Windows oder den Foundry Client selber funktiniort alles wie es soll.

Jemand eine Ahnung was da falsch läuft?

**Comment by himmelweiss** [comment]
Es könnte sein das die "Max Texture Size" der Grafikkarte im Linux Rechner zu gering ist und deshalb die _hires nicht geladen werden kann.

Wenn dem so sein sollte dann die normale lowres Karte stattdessen als Hintergrundbild festlegen.
Die lowres hat zwar einen leichten Offset wodurch dann die Map Notes leicht verschoben sind, also nicht ganz an der richtigen Stelle, aber im groben sollte das dennoch passen.
