### ISSUE TITLE
Error Message while Scene Change with module active

### ISSUE THREAD

**Issue by Sepposaurier** [himmelweiss/dsa5-aventuria-map#7]
First: Thank you for you fantastic module. This is gold...

Problem:
After activating your module on Foundry v11 the Players get the message below while changing every! Scene. Not only to "Aventurien", but changing scenes at all.

If i "take" them to the scenes, they dont get this message. 

Changing them to "Owners" for Aventurien doesnt change it.

![image](https://github.com/himmelweiss/dsa5-aventuria-map/assets/142398649/4290eb26-ce28-42d5-be78-af32e3502410)

**Comment by Sepposaurier** [comment]
The module "dsa5-aventuria-map" contains dependencies using "name" which is deprecated in favor of "id"
The module "dsa5-aventuria-map" contains "dependencies" which is deprecated in favor of "relationships.requires"
The module "dsa5-aventuria-map" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

This is the error message in the setup stage of foundry for the module

**Comment by himmelweiss** [comment]
Sorry for the late reply, module was broken for v11, it should work now again with the latest release.

**Comment by Sepposaurier** [comment]
Oh this is Nixe. I will Test it soon. Thank you very much!

himmelweiss ***@***.***> schrieb am Do., 16. Nov. 2023, 18:18:
